swagger: '2.0'
info:
  title: Bank Argent API documentation
  description: Contains all available API endpoints in this codebase
  version: '1.0.0'
  termsOfService: 'http://swagger.io/terms/'
host: localhost:3001
basePath: /api/v1
schemes:
  - http
paths:
  /user/transaction:
    get:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      operationId: getTransactions
      summary: User transactions for the current month
      description: API for fetching user transactions for the current month
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
      responses:
        '200':
          description: User transactions retrieved successfully
          schema:
            $ref: '#/definitions/TransactionResponse'
        '400':
          description: Invalid Fields
        '401':
          $ref: '#/responses/Unauthorized'
        '404':
          $ref: '#/responses/NotFound'
        '500':
          description: Internal Server Error
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /user/transaction/{transaction_id}:
    put:
      security:
        - Bearer: []
      tags:
        - Transaction Module
      operationId: updateTransactionDetails
      summary: User transaction details
      description: API for updating user transaction details
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: header
          name: Authorization
          description: Attach Bearer JWT token
          type: string
          required: true
        - in: path
          name: transaction_id
          type: string
          minimum: 1
          description: Attach transaction ID to URL
          required: true
        - in: body
          name: body
          description: Update user transaction details
          required: true
          schema:
            $ref: '#/definitions/TransactionDetailsBody'
      responses:
        '200':
          description: Transaction details updated successfully
          schema:
            $ref: '#/definitions/TransactionDetailsResponse'
        '400':
          description: Invalid Fields
        '401':
          $ref: '#/responses/Unauthorized'
        '404':
          $ref: '#/responses/NotFound'
        '500':
          description: Internal Server Error
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
responses:
  NotFound:
    description: The specified resource was not found
    schema:
      $ref: '#/definitions/Error'
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Error'
securityDefinitions:
  Bearer:
    type: apiKey
    name: Authorization
    in: header
definitions:
  TransactionResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: array
        items:
          properties:
            title:
              type: string
            amount:
              type: number
            amountDescription:
              type: string
  TransactionDetailsBody:
    type: object
    properties:
      transaction_id:
        type: string
      date:
        type: string
        format: date-time
      description:
        type: string
      transactionType:
        type: string
      category:
        type: string
      notes:
        type: string
  TransactionDetailsResponse:
    type: object
    properties:
      status:
        type: integer
      message:
        type: string
      body:
        type: object
        properties:
          transaction_id:
            type: string
          date:
            type: string
            format: date-time
          description:
            type: string
          transactionType:
            type: string
          category:
            type: string
          notes:
            type: string
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
