export const PROFILE_TOGGLE_FORM: string = 'PROFILE_TOGGLE_FORM';
export const UPDATE_PROFILE_REQUEST: string = 'UPDATE_PROFILE_REQUEST';
export const UPDATE_PROFILE_SUCCESS: string = 'UPDATE_PROFILE_SUCCESS';
export const UPDATE_PROFILE_FAILURE: string = 'UPDATE_PROFILE_FAILURE';
